services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=event           # FIX: Disamakan dengan MYSQL_ROOT_PASSWORD
      - DB_NAME=db_ticketing    # FIX: Disamakan dengan MYSQL_DATABASE
      - JWT_SECRET=UAS_Kelompok10_Ticketing_2025
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: back-end-db-1  # Biar gampang dipanggil di terminal
    restart: always
    environment:
      MYSQL_DATABASE: db_ticketing
      MYSQL_ROOT_PASSWORD: event
    ports:
      - "3306:3306"
    volumes:
       - db_data:/var/lib/mysql    # PENTING: Agar data tidak hilang saat restart
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pevent"] # FIX: Password disesuaikan
      timeout: 5s
      retries: 10
      interval: 10s

volumes:
  db_data: